config/routes.rb
Okyll::Application.routes.draw do
  get 'try', to: "welcome#login_as_try"
  get 'try/after', to: "welcome#signup_after_try"
  
  scope "/explore" do
    get '/', to: "explore#index"
  end
  
  resources :sites do
    get 'git', on: :new, action: :new_git
    get 'upload', on: :new, action: :new_upload
    
    member do
      get 'preview'
      get 'preview/(:link)', action: :preview, :constraints => { :link => /.*/ }
      
      get 'deploy/:way', action: :deploy
      get 'download'
      get 'settings', to: "settings#index"
      get 'teams', to: "settings#teams"
      get 'deployway', to: "settings#deploy"
    end
    
    resources :templates
    resources :pages
    resources :deploy_tasks
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    delete "/users/sign_out" => "devise/sessions#destroy"
  end
  
  get "dashboard", to: "dashboard#index"

  root 'welcome#index'

  

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @sites = {}
    @sites[:own] = current_user.sites
    @sites[:designer_of] = current_user.designer_of
    @sites[:editor_of] = current_user.editor_of
    @sites[:contributor_of] = current_user.contributor_of
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def method_name
    
  end
end

app/views/dashboard/index.html.slim
.row
  .col-md-9
    .panel-group#accordion
      - @sites.each do |key,sites|
        .panel.panel-default
          .panel-heading
            .panel-title
              a data-toggle="collapse" data-parent="#accordion" href=="##{key}" = "#{key}(#{sites.count})"
            .panel-collapse.collapse.in id=="#{key}"
              .panel-body
                .row
                  - sites.each do |site|
                    .col-md-4
                      .panel.panel-site.site-card
                        .panel-heading
                          = site.name
                          .pull-right
                            = link_to "Edit", site_path(site)
                        .panel-body
                          ul
                            li = "designers = #{site.designers.count}"
                            - site.designers.each do |designer|
                              li = designer.email
                          hr
                          ul
                            li = "editors = #{site.editors.count}"
                            - site.editors.each do |editor|
                              li = editor.email
                          hr
                          ul
                            li = "contributors = #{site.contributors.count}"
                            - site.contributors.each do |contributor|
                              li = contributor.email
                          hr
  .col-md-3
    .panel.panel-success
      .panel-heading.text-center
        i.icon-plus-sign
        '
        | Add New Site
      .panel-body
        = link_to fa_icon("plus-sign large", text: "Create New Site"), new_site_path, class: "btn btn-primary btn-lg btn-block"
        = link_to fa_icon("upload large", text: "Upload a Jekyll Site"), upload_new_site_path, class: "btn btn-primary btn-lg btn-block disabled"
        = link_to fa_icon("github large", text: "Create from Git"), git_new_site_path, class: "btn btn-primary btn-lg btn-block disabled"