config/routes.rb
Okyll::Application.routes.draw do
  get 'try', to: "welcome#login_as_try"
  get 'try/after', to: "welcome#signup_after_try"
  
  scope "/explore" do
    get '/', to: "explore#index"
  end
  
  resources :sites do
    get 'git', on: :new, action: :new_git
    get 'upload', on: :new, action: :new_upload
    
    member do
      get 'preview'
      get 'preview/(:link)', action: :preview, :constraints => { :link => /.*/ }
      
      get 'deploy/:way', action: :deploy
      get 'download'
      get 'settings', to: "settings#index"
      get 'teams', to: "settings#teams"
      get 'deployway', to: "settings#deploy"
    end
    
    resources :templates
    resources :pages
    resources :deploy_tasks
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    delete "/users/sign_out" => "devise/sessions#destroy"
  end
  
  get "dashboard", to: "dashboard#index"

  root 'welcome#index'

  

end

app/views/templates/_form.html.slim
= simple_form_for([@site, @template], html: {class: "form-horizontal"}) do |f|
  = f.error_notification
  .panel.panel-default
    .panel-heading.clearfix
      .form-group
        .col-md-2
          = f.label :name,class: "text-right control-label", required: true
        .col-md-8
          = f.input_field :name, required: true, autofocus: true, class: "form-control"
        .col-md-2
          = f.error :title, class: 'text-danger'
      .form-group
        .col-md-3
          = f.label :default, class: "text-right control-label", required: true
        .col-md-9.form-inline
          = f.input_field :default, as: :boolean, class: "form-control"
    .panel-body
      = f.input :body, as: :text, input_html: {class: "form-control codemirror cm-s-solarized cm-s-light", id: "page_body"}
    .panel-footer.text-center      
        = f.button :submit, class: "btn btn-success btn-lg"

app/views/templates/edit.html.slim
h1 Editing bag

== render 'form'

= link_to 'Show', site_template_path(@site, @template)
'|
= link_to 'Back', site_templates_path(@site)

app/views/templates/index.html.slim
hr
.row
  .col-md-8
    - if @site.templates.blank?
      h1 there is no pages
    .list-group
      - @templates.each do |template|
        .list-group-item.active.clearfix
          .col-md-10
            h4.list-group-item-heading
              = link_to "#{template.name}", [@site, template]
            p.list-group-item-text
              = template.body
          .col-md-1.pull-right
            = link_to fa_icon("trash 2x"), [@site, template], class: "btn btn-danger", :confirm => 'Are you sure?', :method => :delete
      = paginate @templates
  .col-md-4
    .panel.panel-default
      .panel-heading Sider Bar
      .panel-body
        = link_to fa_icon("edit", text: "Add a new Layout"), new_site_template_path(@site), class: "btn btn-success btn-lg btn-block"
    .panel.panel-default
      .panel-heading Sider Bar
      .panel-body Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
h1 Listing Templates

app/views/templates/new.html.slim
h1 New bag

== render 'form'

= link_to 'Back', site_templates_path

app/views/templates/show.html.slim
p#notice = notice
/ 
/ p
/   strong Name:
/   = @template.name
/ p
/   strong body:
/ pre
/   = @template.body

== render 'form'

= link_to 'Edit', edit_site_template_path(@site, @template)
'|
= link_to 'Back', site_templates_path