config/routes.rb
Okyll::Application.routes.draw do
  get 'try', to: "welcome#login_as_try"
  get 'try/after', to: "welcome#signup_after_try"
  
  scope "/explore" do
    get '/', to: "explore#index"
  end
  
  resources :sites do
    get 'git', on: :new, action: :new_git
    get 'upload', on: :new, action: :new_upload
    
    member do
      get 'preview'
      get 'preview/(:link)', action: :preview, :constraints => { :link => /.*/ }
      
      get 'deploy/:way', action: :deploy
      get 'download'
      get 'settings', to: "settings#index"
      get 'teams', to: "settings#teams"
      get 'deployway', to: "settings#deploy"
    end
    
    resources :templates
    resources :pages
    resources :deploy_tasks
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    delete "/users/sign_out" => "devise/sessions#destroy"
  end
  
  get "dashboard", to: "dashboard#index"

  root 'welcome#index'

  

end

app/views/pages/_form.html.slim
= simple_form_for([@site, @page], html: {class: "form-horizontal"}) do |f|
  = f.error_notification
  .panel.panel-default
    .panel-heading.clearfix
      .form-group
        .col-md-2
          = f.label :title, label: "Title",class: "text-right control-label", required: true
        .col-md-8
          = f.input_field :title, required: true, autofocus: true, class: "form-control"
        .col-md-2
          = f.error :title, class: 'text-danger'
      .form-group
        .col-md-2
          = f.label :permalink,class: "control-label", required: true
        .col-md-8
          .input-group
            span.input-group-addon http://domain.name/
            = f.input_field :permalink, class: "form-control"
        .col-md-2
          = f.error :permalink, class: 'text-danger'
      .row
        .form-input.col-md-4
          .col-md-3
            = f.label :published, class: "text-right control-label", required: true
          .col-md-9.form-inline
            = f.input_field :published, as: :boolean, class: "form-control"
        .form-input.col-md-4
          .col-md-3
            = f.label :type, class: "text-right control-label", required: true
          .col-md-9.form-inline
            = f.input_field :type, collection: Page::PAGETYPE, as: :select, class: "form-control"
        .form-input.col-md-4
          = f.input :template, collection: @site.templates.all, prompt: "Choose a Company"
    .panel-body
      = f.input_field :body, as: :text, class: "qeditor form-control", rows: "34"
    .panel-footer.text-center      
        = f.button :submit, class: "btn btn-success btn-lg"

app/views/pages/edit.html.slim
h1 Editing page

== render 'form'

= link_to 'Show', [@page.site, @page]
'|
= link_to 'Back', site_pages_path

app/views/pages/index.html.slim
h1 Listing pages

table
  tr
    th Title
    th Permalink
    th Published
    th Body
    th
    th
    th

  - @pages.each do |page|
    tr
      td = page.title
      td = page.permalink
      td = page.published
      td = page.body
      td = link_to 'Show', site_page_path(page.site,page)
      td = link_to 'Edit', edit_site_page_path(page.site,page)
      td = link_to 'Destroy', site_page_path(page.site,page), :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Page', new_site_page_path

app/views/pages/new.html.slim
== render 'form'

= link_to 'Back', site_pages_path

app/views/pages/show.html.slim
p#notice = notice
/ 
/ p
/   strong Title:
/   = @page.title
/ p
/   strong Permalink:
/   = @page.permalink
/ p
/   strong Published:
/   = @page.published
/ p
/   strong Body:
/   = @page.body
== render 'form'

= link_to 'Edit', edit_site_page_path(@page.site, @page)
'|
= link_to 'Back', site_path(@page.site)