config/routes.rb
Okyll::Application.routes.draw do
  get 'try', to: "welcome#login_as_try"
  get 'try/after', to: "welcome#signup_after_try"
  
  scope "/explore" do
    get '/', to: "explore#index"
  end
  
  resources :sites do
    get 'git', on: :new, action: :new_git
    get 'upload', on: :new, action: :new_upload
    
    member do
      get 'preview'
      get 'preview/(:link)', action: :preview, :constraints => { :link => /.*/ }
      
      get 'deploy/:way', action: :deploy
      get 'download'
      get 'settings', to: "settings#index"
      get 'teams', to: "settings#teams"
      get 'deployway', to: "settings#deploy"
    end
    
    resources :templates
    resources :pages
    resources :deploy_tasks
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    delete "/users/sign_out" => "devise/sessions#destroy"
  end
  
  get "dashboard", to: "dashboard#index"

  root 'welcome#index'

  

end

app/views/layouts/application.html.slim
doctype html
/[if lt IE 7]
  |<html class='no-js lt-ie9 lt-ie8 lt-ie7'>
/[if IE 7]
  |<html class='no-js lt-ie9 lt-ie8'>
/[if IE 8]
  |<html class='no-js lt-ie9'>
/![if gt IE 8]><!
html.no-js
  /!<![endif]

  == render 'head'

  body class=controller.controller_name
    == render 'chromeframe'
    == render 'header'

    .container
      == render 'flashes'
    
    .container
      == yield
    hr
    == render 'footer'

    / Javascript at the bottom for fast page loading
    == render 'javascripts'

app/views/layouts/homepage.html.slim
doctype html
/[if lt IE 7]
  |<html class='no-js lt-ie9 lt-ie8 lt-ie7'>
/[if IE 7]
  |<html class='no-js lt-ie9 lt-ie8'>
/[if IE 8]
  |<html class='no-js lt-ie9'>
/![if gt IE 8]><!
html.no-js
  /!<![endif]

  == render 'head'

  body style="background-image: url('http://d.pr/i/26J9+');"
    == render 'chromeframe'

    == render 'flashes'
    
    == yield
    
    == render 'footer'

    / Javascript at the bottom for fast page loading
    == render 'javascripts'

app/views/layouts/site_dashboard.html.slim
doctype html
/[if lt IE 7]
  |<html class='no-js lt-ie9 lt-ie8 lt-ie7'>
/[if IE 7]
  |<html class='no-js lt-ie9 lt-ie8'>
/[if IE 8]
  |<html class='no-js lt-ie9'>
/![if gt IE 8]><!
html.no-js
  /!<![endif]

  == render 'head'
  
  / Javascript at the bottom for fast page loading
  == javascript_include_tag 'codemirror'
  == javascript_include_tag 'codemirror/modes/xml'
  == javascript_include_tag 'codemirror/modes/javascript'
  == javascript_include_tag 'codemirror/modes/htmlmixed'
  == stylesheet_link_tag 'codemirror'
  == stylesheet_link_tag 'codemirror/themes/solarized.css'
  
  body class=controller.controller_name
    == render 'chromeframe'
    == render 'header'

    .container
      == render 'flashes'
    .container
      .row
        .col-md-2
          .btn-group.pull-left
            = link_to @site.name, @site, class: "btn btn-default"
            button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
              span class="caret"
              span class="sr-only" Toggle Dropdown
            ul.dropdown-menu role="menu"
              - current_user.sites.each do |site|
                - unless site == @site
                  li
                    = link_to site.name, site_path(site)
        .col-md-5
          .btn-group
            = link_to fa_icon("eye-open", text: "Manager Content"), @site, class: "btn"
            = link_to fa_icon("cloud", text: "Manager Layouts"), site_templates_path(@site), class: "btn"
            = link_to fa_icon("download-alt", text: "Manager Assets"), preview_site_path(@site), class: "btn disabled"
        .col-md-5
          .pull-right
            - if @page
              = link_to fa_icon("eye-open", text: "Preview"), preview_site_url(@site) << "/#{@page.permalink}", target: "_blank", class: "btn btn-default"
            - else
              = link_to fa_icon("eye-open", text: "Preview"), preview_site_path(@site), target: "_blank", class: "btn btn-default"
              
            '
            .btn-group.btn-success
              = link_to fa_icon("cloud", text: "Deploy"), site_path(@site), class: "btn btn-success"
              button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown"
                span class="caret"
                span class="sr-only" Toggle Dropdown
              ul.dropdown-menu role="menu"
                li
                  = link_to fa_icon("github", text: "Github Pages"), site_path(@site) << "/deploy/git"
                li
                  = link_to fa_icon("cloud", text: "Amazon S3"), site_path(@site) << "/deploy/s3"
            '
            = link_to fa_icon("download-alt", text: "Download"), preview_site_path(@site), class: "btn btn-default"
            '
            = link_to fa_icon("cogs", text: "Settings"), settings_site_path(@site), class: "btn btn-default"
    .container
      == yield
    hr
    
    == render 'footer'

    / Javascript at the bottom for fast page loading
    == render 'javascripts'

app/views/layouts/site_preview.slim
== yield

css:
  .top-bar {
    position: fixed;
    right: 0;
    left: 0;
    background: red;
  }
.top-bar
  h4
    | params >>> 
    = params
  h4 
    | permalink >>> 
    = params[:link]

app/views/layouts/templates.html.slim
doctype html
/[if lt IE 7]
  |<html class='no-js lt-ie9 lt-ie8 lt-ie7'>
/[if IE 7]
  |<html class='no-js lt-ie9 lt-ie8'>
/[if IE 8]
  |<html class='no-js lt-ie9'>
/![if gt IE 8]><!
html.no-js
  /!<![endif]

  == render 'head'
  == javascript_include_tag 'codemirror'
  == javascript_include_tag 'codemirror/modes/xml'
  == javascript_include_tag 'codemirror/modes/javascript'
  == javascript_include_tag 'codemirror/modes/htmlmixed'
  == stylesheet_link_tag 'codemirror'
  == stylesheet_link_tag 'codemirror/themes/solarized.css'

  body class=controller.controller_name
    == render 'chromeframe'
    == render 'header'

    .container
      == render 'flashes'
    
    .container
      == yield
      hr
    == render 'footer'

    / Javascript at the bottom for fast page loading
    == render 'javascripts'